main: com.njdaeger.enhanceddebugstick.plotsquared.PS_Impl
name: EnhancedDebugStick-PlotSquared
version: ${project.version}
api-version: 1.13
author: NJDaeger
depend:
  - EnhancedDebugStick
  - PlotSquared